### ISSUE TITLE
Document Debian package installation

### ISSUE THREAD

**Issue by farshidtz** [linksmart/thing-directory#21]
The debian packages need to be documented. 

E.g.:

- How to download and install?
- What are the systemctl service configurations (logging, startup)?
- How to configure the directory server?
- How to restart/stop the service?

TBA in https://github.com/linksmart/thing-directory/wiki/Debian-Package

**Comment by blubbfish** [comment]
Fill out the wikipage with all infos :)

**Comment by farshidtz** [comment]
Thanks!
What about the logs?
`journalctl -u thing-directory` doesn't show any.

**Comment by blubbfish** [comment]
stdout is piped to /dev/null at the moment,
stderr is visible with journalctl

**Comment by blubbfish** [comment]
Documentation is now up to date
