### ISSUE TITLE
DNS-SD publish error after reboot (systemctl service)

### ISSUE THREAD

**Issue by farshidtz** [linksmart/thing-directory#23]
```
Failed to register DNS-SD service: Could not determine host IP addresses
```

A service restart will solve it. 

Maybe it needs some additional pre-condition before starting the process?

**Comment by farshidtz** [comment]
@blubbfish any idea?

**Comment by blubbfish** [comment]
Fixed in: https://github.com/linksmart/ci-scripts/commit/feb71a7c7e6f7e37c87b99dca080a28d110a0e9d#diff-fe04767a81ab607cee78fb54d9e919a3
