### ISSUE TITLE
Upgrading debian package replaces the config file

### ISSUE THREAD

**Issue by farshidtz** [linksmart/thing-directory#25]
Upgrading debian package replaces the config file with a new one even if changed locally by the user. 

Any way around this? 

I've see some package installers ask the user to leave the config files intact.

**Comment by blubbfish** [comment]
there is a way for debian packages to check if the file in the update packet was changed and differ from the version that is installed.

**Comment by blubbfish** [comment]
For a quick fix the default filename is now `settings.json.example` and this file will be replace when update. 
After an installation you must copy that to `settings.json` and customise it.
 - Changed the instructions in the wiki to that.

**Comment by blubbfish** [comment]
https://www.debian.org/doc/manuals/maint-guide/dother.de.html#conffiles

**Comment by blubbfish** [comment]
postinst scipt now uses ucf to compare configfiles
