### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by yadudoc** [linksmart/thing-directory#37]
I'm going over the documentation as part of the JOSS review process and it looks like most things are in great shape. The API documentation with Swagger is very nice. I've gotten the application built and launched with docker and also with just go build. At this point, I usually go to the contributing guide, most commonly a separate file (CONTRIBUTING.*) in the project root that covers how to go about testing locally to make sure everything is working fine. Having CI/CD is great, but testing locally is quicker. 

While the contrib file could describe many things, I especially find descriptions of the dev workflow and PR process especially useful. I'm tagging this under `Community guidelines` as part of the JOSS review (https://github.com/openjournals/joss-reviews/issues/3075)

**Comment by farshidtz** [comment]
Thanks @yadudoc for your feedback. I agree that a CONTRIBUTING.md file is common, but we have a wiki and having parallel places for documentations may add some confusion.

I [added missing details](https://github.com/linksmart/thing-directory/commit/cc5bb8d7b04105abff7420b7083364fea9ff927c) in regards to build, testing, and execution to the development section of the README. There is also a contributing section there.

Do you think that covers your concerns now?

**Comment by yadudoc** [comment]
I believe so. As your project scales, it might be worth considering setting up issue templates to indicate to users how best to report a bug, or specifics regarding a feature request. I'll mark this one closed.
