### ISSUE TITLE
Citation to a more recent survey paper

### ISSUE THREAD

**Issue by yadudoc** [linksmart/thing-directory#39]
Based on a quick search on gscholar about surveys on IoT discovery techniques, I see that there's a more recent paper from 2020 here: https://doi.org/10.1016/j.iot.2020.100293 that might be worth considering adding to the related work section.

**Comment by yadudoc** [comment]
Related to https://github.com/openjournals/joss-reviews/issues/3075.

**Comment by dschowta** [comment]
Thank you for the pointer. I added this to the related work section. The diff can be seen here:  https://github.com/linksmart/thing-directory/commit/bb08f5efa6cdf2d5b357e2491e306d8f386f8feb

**Comment by yadudoc** [comment]
Thanks @dschowta, I see the changes on the pdf now. Let me close this one.
