### ISSUE TITLE
Access control for Demo

### ISSUE THREAD

**Issue by yadudoc** [linksmart/thing-directory#40]
Currently, the demo page here: https://github.com/linksmart/thing-directory/wiki/Demo appears to be read-only. I have run a few queries from the swagger UI, and that does work. However, the majority of the functionality requires authorization which doesn't appear to be possible as a user. Can you clarify whether the access control section is relevant to the hosted service or if it applies only to the scenario where the user sets up the service?

Related to: https://github.com/openjournals/joss-reviews/issues/3075

**Comment by farshidtz** [comment]
The demo was setup to support W3C WoT plugfests, first [here](https://github.com/w3c/wot-testing/blob/main/events/2020.06.Online/prototypes/linksmart.md) and continued every 6 months. The data in this demo comes from the plugfests too; see [here](https://github.com/farshidtz/wot-testing-directory-sync). In last month's plugfest, this demo instance was used to [integrate the directory with NodeRED](https://github.com/w3c/wot-testing/blob/main/events/2021.03.Online/Results/2021-03-05-nodered-directory-ktoumura.pdf).

I agree that the authentication section is consufusing without providing credentials or client secret. I [added a note](https://github.com/linksmart/thing-directory/wiki/Demo/_compare/f194572facbeba5d98cc4f876189802c44530154...e14bf32fde96ebee7fcd88024c514a42c11affdb) to hopefully clarify this. As mentioned in the change, the access details are provided to W3C WoT Plugfest participants. The participants are W3C WoT members or guests.

**Comment by yadudoc** [comment]
Okay, I think the clarification does help. So, in this case, setting up the service locally with auth, and having a swagger UI point at that for manual testing is probably too much effort. I think I'm going to have to be satisfied with the tests. I'll close this issue.

**Comment by farshidtz** [comment]
If you want the the access details, I can send to you by email. But you don't need to worry about the authentication implementation as this is a well tested [library](https://github.com/linksmart/go-sec) used by several other services. It is not a part of this project.

**Comment by yadudoc** [comment]
Oh! that would be wonderful. I wanted to try adding a couple of mock devices and query them over the REST API.

**Comment by farshidtz** [comment]
Sent you an email. Let me know if you face any issues.

**Comment by yadudoc** [comment]
@farshidtz, With the basic auth credentials I was able to register new things and later query them. Thanks for sharing the keys, this definitely made testing out the basic functionality much easier.
