### ISSUE TITLE
Migrate to Github Actions

### ISSUE THREAD

**Issue by farshidtz** [linksmart/thing-directory#8]
Migrate the following TravisCI workflow to Github Actions:

https://github.com/linksmart/thing-directory/blob/3713365c2fb6e16aca1278df33be9743efb7fec7/.travis.yml

**Comment by farshidtz** [comment]
Example: https://github.com/linksmart/historical-datastore/blob/master/.github/workflows/build.yml

**Comment by farshidtz** [comment]
FYI: travis file is updated in branch to run tests as well: https://github.com/linksmart/thing-directory/blob/update-tests/.travis.yml

**Comment by farshidtz** [comment]
Added DOCKERHUB_USER and DOCKERHUB_TOKEN secrets for actions.

**Comment by farshidtz** [comment]
https://github.com/linksmart/thing-directory/compare/eda3fb0..433dbfd

Made some changes to reduce replicated logic. 

Also, removed the separate snapshots. The goal was to make it easy to download on devices, but the snapshots are only available to logged in users.

It would still be good to move these to another script:
https://github.com/linksmart/thing-directory/blob/433dbfdb4dc8f161e6b6d7ed1ad8a1dd0654b499/.github/workflows/go.yml#L96

**Comment by blubbfish** [comment]
* Implemented in dbc1d135f1d7009dd5d6b7847cc7e32a18d43aa0
* Improved in 433dbfdb4dc8f161e6b6d7ed1ad8a1dd0654b499
